ALTER TABLE CONTACT DROP CONSTRAINT CONTACT_CLIENTS_FK;
ALTER TABLE GAMES DROP CONSTRAINT GAMES_PUBLISH_FK;
ALTER TABLE ORDERS DROP CONSTRAINT ORDERS_CLIENTS_FK;
ALTER TABLE ORDERS DROP CONSTRAINT ORDERS_GAMES_FK;

DROP TABLE ORDERS;
DROP TABLE CONTACT;
DROP TABLE GAMES;
DROP TABLE CLIENTS;
DROP TABLE PUBLISH;

DROP SEQUENCE SEQ_CLIENTS;
DROP SEQUENCE SEQ_GAMES;
DROP SEQUENCE SEQ_ORDERS;
DROP SEQUENCE SEQ_PUBLISH;

DROP PACKAGE BODY PKG_SHOP;
DROP PACKAGE PKG_SHOP;